# Copyright (c) 2026 Ivan Skachek (github.com/IvanSFlowGit)
# PolyForm Noncommercial License 1.0.0 - see LICENSE and NOTICE.
# Commercial use requires a separate licence from the author.
"""Append-only audit trail for dunning decisions.

Two backends behind one two-method interface (``record`` and ``for_invoice``):

* :class:`SqliteDecisionAudit` - the FastAPI app on Fly, and every offline test.
* :class:`PostgresDecisionAudit` - the Lambda slice, against RDS. ``pg8000`` is
  imported lazily so the offline suite never needs it installed.

A row carries the invoice id, the rule that fired, the validated input and the
decision. No name, no email, no card: the decision input does not accept them,
so they cannot reach this table.

There is no update or delete method on either backend.
"""

from __future__ import annotations

import json
import os
import sqlite3
import ssl
import threading
import uuid
from pathlib import Path

DECISION_AUDIT_DB_ENV = "PAYPILOT_DECISION_AUDIT_DB_PATH"

# Kept portable between SQLite and Postgres on purpose: text ids generated by
# the application, ISO-8601 timestamps as text, JSON as text. The Postgres copy
# is app/decision_schema.sql and tests/test_decision.py asserts the two agree.
SQLITE_SCHEMA = """
CREATE TABLE IF NOT EXISTS decision_audit (
    id          TEXT PRIMARY KEY,
    invoice_id  TEXT NOT NULL,
    rule_fired  TEXT NOT NULL,
    decided_at  TEXT NOT NULL,
    input       TEXT NOT NULL,
    decision    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_decision_audit_invoice
    ON decision_audit (invoice_id, decided_at);
"""

#: Most rows a lookup returns. An invoice with more decisions than this is
#: being hammered, and the newest rows are the ones worth reading.
LOOKUP_LIMIT = 50


def _row(audit_id: str, decision: dict) -> tuple:
    return (
        audit_id,
        decision["invoice_id"],
        decision["rule_fired"],
        decision["decided_at"],
        json.dumps(decision["input"], sort_keys=True),
        json.dumps(decision, sort_keys=True),
    )


def _as_record(audit_id, rule_fired, decided_at, decision_json) -> dict:
    return {
        "audit_id": audit_id,
        "rule_fired": rule_fired,
        "decided_at": decided_at,
        "decision": json.loads(decision_json),
    }


class SqliteDecisionAudit:
    """SQLite decision audit. ``:memory:`` unless a path or the env var is set."""

    def __init__(self, path: str | Path | None = None) -> None:
        self.path = str(path or os.getenv(DECISION_AUDIT_DB_ENV) or ":memory:")
        if self.path != ":memory:":
            Path(self.path).parent.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()
        self._conn = sqlite3.connect(self.path, check_same_thread=False)
        self._conn.executescript(SQLITE_SCHEMA)
        self._conn.commit()

    def record(self, decision: dict) -> str:
        audit_id = uuid.uuid4().hex
        with self._lock:
            self._conn.execute(
                "INSERT INTO decision_audit "
                "(id, invoice_id, rule_fired, decided_at, input, decision) "
                "VALUES (?, ?, ?, ?, ?, ?)",
                _row(audit_id, decision),
            )
            self._conn.commit()
        return audit_id

    def for_invoice(self, invoice_id: str) -> list[dict]:
        with self._lock:
            rows = self._conn.execute(
                "SELECT id, rule_fired, decided_at, decision FROM decision_audit "
                "WHERE invoice_id = ? ORDER BY decided_at DESC, rowid DESC LIMIT ?",
                (invoice_id, LOOKUP_LIMIT),
            ).fetchall()
        return [_as_record(*r) for r in rows]


class PostgresDecisionAudit:
    """Postgres decision audit for the Lambda slice.

    Connection settings come from the standard libpq names (``PGHOST``,
    ``PGPORT``, ``PGDATABASE``, ``PGUSER``, ``PGPASSWORD``). TLS is required and
    the server certificate is verified against ``PGSSLROOTCERT`` (the RDS CA
    bundle shipped in the deployment package); there is no unverified fallback.

    One connection is held per warm Lambda container and re-opened once if it
    has gone stale between invocations.
    """

    def __init__(self, env: dict | None = None) -> None:
        self._env = env if env is not None else os.environ
        self._conn = None

    def _connect(self):
        env = self._env
        cafile = env.get("PGSSLROOTCERT")
        if not cafile:
            raise RuntimeError("PGSSLROOTCERT is not set; refusing an unverified TLS connection")

        import pg8000.native  # lazy: not needed by the offline suite

        context = ssl.create_default_context(cafile=cafile)
        return pg8000.native.Connection(
            user=env["PGUSER"],
            password=env["PGPASSWORD"],
            host=env["PGHOST"],
            port=int(env.get("PGPORT", "5432")),
            database=env["PGDATABASE"],
            ssl_context=context,
            timeout=5,
        )

    def _run(self, sql: str, **params):
        for attempt in (1, 2):
            try:
                if self._conn is None:
                    self._conn = self._connect()
                return self._conn.run(sql, **params)
            except Exception:
                # A stale connection from a frozen container fails on first use.
                # Drop it and try exactly once more; a second failure propagates
                # and the caller fails closed. Retrying the INSERT is safe because
                # the row id is generated before the first attempt: if that
                # attempt did land, the retry hits the primary key and fails,
                # so the worst case is a 503 for a recorded row, never two rows.
                try:
                    if self._conn is not None:
                        self._conn.close()
                except Exception:  # noqa: BLE001
                    pass
                self._conn = None
                if attempt == 2:
                    raise
        raise AssertionError("unreachable")

    def record(self, decision: dict) -> str:
        audit_id = uuid.uuid4().hex
        values = _row(audit_id, decision)
        self._run(
            "INSERT INTO decision_audit "
            "(id, invoice_id, rule_fired, decided_at, input, decision) "
            "VALUES (:id, :invoice_id, :rule_fired, :decided_at, :input, :decision)",
            id=values[0],
            invoice_id=values[1],
            rule_fired=values[2],
            decided_at=values[3],
            input=values[4],
            decision=values[5],
        )
        return audit_id

    def for_invoice(self, invoice_id: str) -> list[dict]:
        # Newest first by decided_at (millisecond precision). Two decisions in the
        # same millisecond have no defined order here; SQLite breaks the tie by rowid.
        rows = self._run(
            "SELECT id, rule_fired, decided_at, decision FROM decision_audit "
            "WHERE invoice_id = :invoice_id ORDER BY decided_at DESC LIMIT :limit",
            invoice_id=invoice_id,
            limit=LOOKUP_LIMIT,
        )
        return [_as_record(*r) for r in rows]

    def ensure_schema(self, schema_sql: str) -> None:
        """Apply the schema. Idempotent (every statement is IF NOT EXISTS)."""
        for statement in split_sql_statements(schema_sql):
            self._run(statement)


def split_sql_statements(schema_sql: str) -> list[str]:
    """Split a schema file into statements, dropping ``--`` line comments FIRST.

    Splitting on ``;`` before removing comments sent a comment fragment to
    Postgres as a statement: the schema header's prose contained a semicolon.
    Found against a real Postgres, not by the offline suite. The schema has no
    string literals, so a ``--`` is always a comment here.
    """
    code = "\n".join(line.split("--", 1)[0] for line in schema_sql.splitlines())
    return [s.strip() for s in code.split(";") if s.strip()]
