# Copyright (c) 2026 Ivan Skachek (github.com/IvanSFlowGit)
# PolyForm Noncommercial License 1.0.0 - see LICENSE and NOTICE.
# Commercial use requires a separate licence from the author.
"""Render docs/recharge-error-types.md from app/recharge_map.py.

The table is generated so it cannot drift from the code that decides; a test
re-renders it and fails if the committed file differs.

    python scripts/render_recharge_table.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.recharge_map import (  # noqa: E402
    NOT_CUSTOMER,
    PUBLISHED_ERROR_TYPES,
    classify_error_type,
)

OUT = ROOT / "docs" / "recharge-error-types.md"

PILES = {
    "customer": "1. Customer has to act",
    "retry": "2. Recharge retries; no email while a retry is scheduled",
    "store": "3. Store or system problem; nobody is emailed",
}


def pile(code: str) -> str:
    decision = classify_error_type(code)
    if decision == NOT_CUSTOMER:
        return "store"
    if decision == "generic_decline":
        return "retry"
    return "customer"


def render() -> str:
    rows = sorted(PUBLISHED_ERROR_TYPES)
    counts = {key: sum(1 for c in rows if pile(c) == key) for key in PILES}
    lines = [
        "# How PayPilot sorts Recharge's failure reasons",
        "",
        "Generated by `scripts/render_recharge_table.py` from `app/recharge_map.py`. Do not edit by hand.",
        "",
        "Source of the list and of the two flag columns: Recharge, \"Managing order errors\"",
        "(support.getrecharge.com/hc/en-us/articles/22181648082839), read 2026-09-30.",
        "The pile is PayPilot's own decision, and it is the part worth arguing with.",
        "",
        f"{len(rows)} error types: "
        + ", ".join(f"{counts[k]} in pile {PILES[k][0]}" for k in PILES) + ".",
        "",
    ]
    for key, title in PILES.items():
        lines += [f"## {title}", "",
                  "| Error type | Retried by Recharge | Hard decline | PayPilot code |",
                  "|---|---|---|---|"]
        for code in rows:
            if pile(code) != key:
                continue
            retried, hard = PUBLISHED_ERROR_TYPES[code]
            decision = classify_error_type(code)
            shown = "none, not emailed" if decision == NOT_CUSTOMER else f"`{decision}`"
            lines.append(f"| `{code}` | {'yes' if retried else 'no'} | "
                         f"{'yes' if hard else 'no'} | {shown} |")
        lines.append("")
    lines += ["An error type that is not on this list is acknowledged and not emailed about "
              "until someone adds it.", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
